"""value

Revision ID: 122efe238e95
Revises: 64911b7b909e
Create Date: 2025-01-25 20:03:43.144759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '122efe238e95'
down_revision = '64911b7b909e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controller', sa.Column('value', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controller', 'value')
    # ### end Alembic commands ###
