"""controller

Revision ID: 64911b7b909e
Revises: 097e9ec87ed0
Create Date: 2025-01-24 17:57:12.272121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64911b7b909e'
down_revision = '097e9ec87ed0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('value', sa.Integer(), nullable=True))
    op.drop_column('sensor', 'max_value')
    op.drop_column('sensor', 'min_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('min_value', sa.INTEGER(), nullable=False))
    op.add_column('sensor', sa.Column('max_value', sa.INTEGER(), nullable=False))
    op.drop_column('sensor', 'value')
    # ### end Alembic commands ###
