"""value

Revision ID: 9b8407f18b86
Revises: 122efe238e95
Create Date: 2025-01-25 20:12:22.200314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b8407f18b86'
down_revision = '122efe238e95'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('value', sa.Integer(), nullable=True))
    op.drop_column('message', 'message')
    op.drop_column('message', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.add_column('message', sa.Column('message', sa.VARCHAR(), nullable=False))
    op.drop_column('message', 'value')
    # ### end Alembic commands ###
